meta:
  name:     (( param "Please name your pipeline" ))
  pipeline: (( grab meta.name ))
  target:   (( param "Please identify the name of the target Concourse CI" ))
  image:
    type: docker-image
    source:
      repository: starkandwayne/concourse

  github:
    uri:          (( concat "git@github.com:" meta.github.owner "/" meta.github.repo ))
    owner:        (( param "Please specify the name of the user / organization that owns the Github repository" ))
    repo:         (( param "Please specify the name of the Github repository" ))
    branch:       master
    private_key:  (( param "Please generate an SSH Deployment Key for this repo and specify it here" ))
    access_token: (( param "Please generate a Personal Access Token and specify it here (read-only for repos, to avoid rate limiting)" ))
groups:
- name: update-all-cf-buildpacks
  jobs:
  - binary-buildpack
  - go-buildpack
  - ruby-buildpack
  - java-buildpack

jobs:
- name: binary-buildpack
  serial: true
  plan:
  - { get: git }
  - { get: binary-buildpack, trigger: true, params: {globs: ["*cflinuxfs3*.zip"]} }
  - task: update-script
    config:
      platform: linux
      image_resource: (( grab meta.image ))
      inputs:
      - name: git
      - name: binary-buildpack
      outputs:
      - name: pushme
      params:
        GITHUB_REPO: binary-buildpack
        BUILDPACK_NAME: binary_buildpack
      run:
        path: git/ci/scripts/update-buildpack.sh
  - put: git
    params:
      rebase: true
      repository: pushme

- name: go-buildpack
  serial: true
  plan:
  - { get: git }
  - { get: go-buildpack, trigger: true, params: {globs: ["*cflinuxfs3*.zip"]} }
  - task: update-script
    config:
      platform: linux
      image_resource: (( grab meta.image ))
      inputs:
      - name: git
      - name: go-buildpack
      outputs:
      - name: pushme
      params:
        GITHUB_REPO: go-buildpack
        BUILDPACK_NAME: go_buildpack
      run:
        path: git/ci/scripts/update-buildpack.sh
  - put: git
    params:
      rebase: true
      repository: pushme

- name: ruby-buildpack
  serial: true
  plan:
  - { get: git }
  - { get: ruby-buildpack, trigger: true, params: {globs: ["*cflinuxfs3*.zip"]} }
  - task: update-script
    config:
      platform: linux
      image_resource: (( grab meta.image ))
      inputs:
      - name: git
      - name: ruby-buildpack
      outputs:
      - name: pushme
      params:
        GITHUB_REPO: ruby-buildpack
        BUILDPACK_NAME: ruby_buildpack
      run:
        path: git/ci/scripts/update-buildpack.sh
  - put: git
    params:
      rebase: true
      repository: pushme

- name: java-buildpack
  serial: true
  plan:
  - { get: git }
  - { get: java-buildpack, trigger: true }
  - task: update-script
    config:
      platform: linux
      image_resource: (( grab meta.image ))
      inputs:
      - name: git
      - name: java-buildpack
      outputs:
      - name: pushme
      params:
        GITHUB_REPO: java-buildpack
        BUILDPACK_NAME: java_buildpack
      run:
        path: git/ci/scripts/update-buildpack.sh
  - put: git
    params:
      rebase: true
      repository: pushme
resources:
- name: git
  type: git
  source:
    uri:         (( grab meta.github.uri ))
    branch:      (( grab meta.github.branch ))
    private_key: (( grab meta.github.private_key ))

- name: binary-buildpack
  type: github-release
  check_every: 10m
  source:
    owner: cloudfoundry
    repository: binary-buildpack
    access_token: (( grab meta.github.access_token ))

- name: go-buildpack
  type: github-release
  check_every: 10m
  source:
    owner: cloudfoundry
    repository: go-buildpack
    access_token: (( grab meta.github.access_token ))

- name: ruby-buildpack
  type: github-release
  check_every: 10m
  source:
    owner: cloudfoundry
    repository: ruby-buildpack
    access_token: (( grab meta.github.access_token ))

- name: java-buildpack
  type: github-release
  check_every: 10m
  source:
    owner: cloudfoundry
    repository: java-buildpack
    access_token: (( grab meta.github.access_token ))