meta:
  name: update-all-cf-buildpacks
  target: pipes@cfcommunity
  # url: https://ci2.starkandwayne.com team: starkandwayne
  url:     https://pipes.starkandwayne.com
  team:    cfcommunity

  initial_version: 0.2.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  github:
    owner: starkandwayne
    repo: update-all-cf-buildpacks
    private_key: ((github-private-key))
    access_token: ((github-access-token))

  dockerhub:
    username: ((docker-hub.username))
    password: ((docker-hub.password))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-2
    access_key:  ((aws-cfcommunity.access))
    secret_key:  ((aws-cfcommunity.secret))

  chartmuseum:
    user: ((chartmuseum.username))
    pass: ((chartmuseum.password))

  slack:
    webhook:       ((slack.webhook))
    username:      ((slack.username))
    icon:          ((slack-icon))
    channel:       "#update-all-cf-buildpacks"
