# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: starkandwayne/update-all-cf-buildpacks
  tag: latest
  pullPolicy: Always
  # pullPolicy: IfNotPresent
